### ISSUE TITLE
Add 11.5

### ISSUE THREAD

**Issue by uumas** [rikumax25/3SDSetup#16]
Please add support for 11.5.
I think it'll not be too hard, because it's the same as 11.4, so just add 5 as an option for the third box, make it be like 11.4 is now and remove dsiwarehax from 11.4.

**Comment by jorgev259** [comment]
dsiwarehax is not even working, fixing this later since im changing the flow of the app a little. Maybe next week

**Comment by jorgev259** [comment]
https://github.com/rikumax25/3SDSetup/commit/87e0e04636cee101924ada690f76803b49e4bff7 sorry for taking so long ;-;
